{{- if .Values.service.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-service"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}-service"
    aragon.org/environment: "{{ .Values.environment }}"
spec:
  {{- if not .Values.service.autoscaling.enabled }}
  replicas: {{ .Values.service.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.service.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        aragon.org/application: "{{ include "chart.name" . }}-service"
        aragon.org/environment: "{{ .Values.environment }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "heartbeat"
              containerPort: {{ .Values.service.config.heartbeatPort | default 8081 }}
            - name: "reveal"
              containerPort: {{ .Values.service.config.revealPort | default 9082 }}
            - name: "settlements"
              containerPort: {{ .Values.service.config.settlementsPort | default 9083 }}
            - name: "monitorkeeper"
              containerPort: {{ .Values.service.config.monitorKeeperPort | default 9084 }}
            - name: "notifyscan"
              containerPort: {{ .Values.service.config.notificationScannerPort | default 9085 }}
            - name: "notifysen"
              containerPort: {{ .Values.service.config.notificationSenderPort | default 9086 }}
            - name: "contractmonitor"
              containerPort: {{ .Values.service.config.contractMonitorPort | default 9087 }}
          env:
            - name: SERVICE_PORT_HEARTBEAT
              value: {{ .Values.service.config.heartbeatPort | default 8081 | quote }}
            - name: SERVICE_PORT_REVEAL
              value: {{ .Values.service.config.revealPort | default 9082 | quote }}
            - name: SERVICE_PORT_SETTLEMENTS
              value: {{ .Values.service.config.settlementsPort | default 9083 | quote }}
            - name: SERVICE_PORT_MONITOR_KEEPER
              value: {{ .Values.service.config.monitorKeeperPort | default 9084 | quote }}
            - name: SERVICE_PORT_NOTIFICATION_SCANNER
              value: {{ .Values.service.config.notificationScannerPort | default 9085 | quote }}
            - name: SERVICE_PORT_NOTIFICATION_SENDER
              value: {{ .Values.service.config.notificationSenderPort | default 9086 | quote }}
            - name: SERVICE_PORT_CONTRACT_MONITOR
              value: {{ .Values.service.config.contractMonitorPort | default 9087 | quote }}
            - name: ETHERSCAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serviceSecretName" . }}
                  key: etherscanApiKey 
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: clientUrl
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serviceSecretName" . }}
                  key: privateKey
            - name: EMAIL_FROM_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: emailFromDefault
            - name: POSTMARK_TEMPLATE_ALIAS_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: postmarkTemplateAliasVerify
            - name: NETWORK
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: network
            - name: COURT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: courtAddress
            - name: RPC
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: rpc
            - name: GAS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: gas
            - name: GAS_PRICE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: gasPrice
            - name: WEB3_POLLING_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serviceConfigName" . }}
                  key: web3PollingInterval
          args:
            - "npm"
            - "run"
            - "start:services"
          readinessProbe:
              httpGet:
                  path: /
                  port: {{ .Values.service.config.heartbeatPort | default 8081 }}
              initialDelaySeconds: 30
              periodSeconds: 30
          livenessProbe:
              httpGet:
                  path: /
                  port: {{ .Values.service.config.heartbeatPort | default 8081 }}
              initialDelaySeconds: 30
              periodSeconds: 30
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
      {{- with .Values.service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}