{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-service"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "heartbeat"
      port: {{ .Values.service.config.heartbeatPort | default 8081 }}
      targetPort: {{ .Values.service.config.heartbeatPort | default 8081 }}
      protocol: TCP
    - name: "reveal"
      port: {{ .Values.service.config.revealPort | default 9082 }}
      targetPort: {{ .Values.service.config.revealPort | default 9082 }}
      protocol: TCP
    - name: "settlements"
      port: {{ .Values.service.config.settlementsPort | default 9083 }}
      targetPort: {{ .Values.service.config.settlementsPort | default 9083 }}
      protocol: TCP
    - name: "monitor-keeper"
      port: {{ .Values.service.config.monitorKeeperPort | default 9084 }}
      targetPort: {{ .Values.service.config.monitorKeeperPort | default 9084 }}
      protocol: TCP
    - name: "notifcation-scanner"
      port: {{ .Values.service.config.notificationScannerPort | default 9085 }}
      targetPort: {{ .Values.service.config.notificationScannerPort | default 9085 }}
      protocol: TCP
    - name: "notification-sender"
      port: {{ .Values.service.config.notificationSenderPort | default 9086 }}
      targetPort: {{ .Values.service.config.notificationSenderPort | default 9086 }}
      protocol: TCP
    - name: "contract-monitor"
      port: {{ .Values.service.config.contractMonitorPort | default 9087 }}
      targetPort: {{ .Values.service.config.contractMonitorPort | default 9087 }}
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}-service"
    aragon.org/environment: "{{ .Values.environment }}"
{{- end -}}