{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-service"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: "heartbeat"
      port: 9081
      targetPort: 9081
      protocol: TCP
    - name: "reveal"
      port: 9082
      targetPort: 9082
      protocol: TCP
    - name: "settlements"
      port: 9083
      targetPort: 9083
      protocol: TCP
    - name: "monitor-keeper"
      port: 9084
      targetPort: 9084
      protocol: TCP
    - name: "notifcation-scanner"
      port: 9085
      targetPort: 9085
      protocol: TCP
    - name: "notification-sender"
      port: 9086
      targetPort: 9086
      protocol: TCP
    - name: "contract-monitor"
      port: 9087
      targetPort: 9087
      protocol: TCP
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}-service"
    aragon.org/environment: "{{ .Values.environment }}"
{{- end -}}