{{- if .Values.app.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-app"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}-app"
    aragon.org/environment: "{{ .Values.environment }}"
{{- end -}}