{{- if not .Values.secret.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.fullname" . }}-secret"
type: Opaque
data:
  db_host: {{ .Values.secret.db_host | default "" | quote | b64enc }}
  db_name: {{ .Values.secret.db_name | default "" | quote | b64enc }}
  db_pass: {{ .Values.secret.db_pass | default "" | quote | b64enc }}
  db_port: {{ .Values.secret.db_port | default "" | quote | b64enc }}
  db_user: {{ .Values.secret.db_user | default "" | quote | b64enc }}
  etherscan_api_key: {{ .Values.secret.etherscan_api_key | default "" | quote | b64enc }}
{{- end -}}