{{- if not .Values.config.existingConfigMap -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "chart.configName" . }}
data:
  network: "{{ .Values.config.network }}"
  workerPort: "{{ .Values.config.workerPort }}"
  serverPort: "{{ .Values.config.serverPort }}"
  corsWhitelist: "{{ .Values.config.corsWhitelist }}"
{{- end -}}