apiVersion: v1
kind: Secret
metadata:
  name: v2-datafeed-secret
type: Opaque
data:
  dbName: {{ .Values.secret.dbName | default "" | b64enc }}
  dbHost: {{ .Values.secret.dbHost | default "" | b64enc }}
  dbPort: {{ .Values.secret.dbPort | default "" | b64enc }}
  dbUser: {{ .Values.secret.dbUser | default "" | b64enc }}
  dbPass: {{ .Values.secret.dbPass | default "" | b64enc }}
