apiVersion: v1
kind: Secret
metadata:
  name: v2-datafeed-secret
type: Opaque
data:
  dbName: {{ .Values.secret.dbName | b64enc }}
  dbHost: {{ .Values.secret.dbHost | b64enc }}
  dbPort: {{ .Values.secret.dbPort | b64enc }}
  dbUser: {{ .Values.secret.dbUser | b64enc }}
  dbPass: {{ .Values.secret.dbPass | b64enc }}
