apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.secretName" . }}
type: Opaque
data:
  dbName: {{ default .Values.secret.dbName "default" | b64enc }}
  dbHost: {{ default .Values.secret.dbHost "default" | b64enc }}
  dbPort: {{ default .Values.secret.dbPort "default" | b64enc }}
  dbUser: {{ default .Values.secret.dbUser "default" | b64enc }}
  dbPass: {{ default .Values.secret.dbPass "default" | b64enc }}