apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.config.serverPort }}
      protocol: TCP
      name: server
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
