{{- if and (not .Values.service.secret.existingSecret) .Values.service.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.fullname" . }}-service-secret"
type: Opaque
data:
  postmarkApiToken: {{ .Values.service.secret.postmarkApiToken | default "" | quote | b64enc }}
  etherscanApiKey: {{ .Values.service.secret.etherscanApiKey | default "" | quote | b64enc }}
  privateKey: {{ .Values.service.secret.privateKey | default "" | quote | b64enc }}
  courtAddress: {{ .Values.service.secret.courtAddress | default "" | quote | b64enc }}
  dbName: {{ .Values.service.secret.dbName | default "" | quote | b64enc }}
  dbHost: {{ .Values.service.secret.dbHost | default "" | quote | b64enc }}
  dbPort: {{ .Values.service.secret.dbPort | default "" | quote | b64enc }}
  dbUser: {{ .Values.service.secret.dbUser | default "" | quote | b64enc }}
  dbPass: {{ .Values.service.secret.dbPass | default "" | quote | b64enc }}
{{- end -}}