{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.secretName" . }}
type: Opaque
data:
  jwt_key: {{ .Values.secret.jwt_key | default "" | b64enc }}
  pg_connection_string: {{ .Values.secret.pg_connection_string | default "" | b64enc }}
  postmark_server_api_token: {{ .Values.secret.postmark_server_api_token | default "" | b64enc }}
  db_host: {{ .Values.secret.db_host | default "" | b64enc }}
  db_name: {{ .Values.secret.db_name | default "" | b64enc }}
  db_pass: {{ .Values.secret.db_pass | default "" | b64enc }}
  db_port: {{ .Values.secret.db_port | default "" | b64enc }}
  db_user: {{ .Values.secret.db_user | default "" | b64enc }}
{{- end -}}