apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: api
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: metrics
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}"
    aragon.org/environment: "{{ .Values.environment }}"
