{{- if .Values.server.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-server"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}-server"
    aragon.org/environment: "{{ .Values.environment }}"
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        aragon.org/application: "{{ include "chart.name" . }}-server"
        aragon.org/environment: "{{ .Values.environment }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "app"
              containerPort: {{ .Values.server.config.port  | default 8000 }}
            - name: "metrics"
              containerPort: {{ .Values.server.config.metricsPort  | default 9091 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.server.config.port  | default 8000 | quote }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbName
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbUser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: dbPass
            - name: CORS_WHITELIST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: corsWhitelist
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: sessionSecret
            - name: SESSION_SECURE
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: sessionSecure
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: adminEmail
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: adminPass
            - name: EMAIL_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: emailJwtPrivate
            - name: POSTMARK_SERVER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: postmarkServerApiToken
            - name: SERVER_METRICS_PORT
              value: {{ .Values.server.config.metricsPort  | default 9091 | quote }}
            - name: EMAIL_FROM_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: emailFromDefault
            - name: POSTMARK_TEMPLATE_ALIAS_VERIFY
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: postmarkTemplateAliasVerify
            - name: NETWORK
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: network
            - name: COURT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: courtAddress
            - name: RPC
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: rpc
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.serverSecretName" . }}
                  key: privateKey
            - name: GAS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: gas
            - name: GAS_PRICE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: gasPrice
            - name: WEB3_POLLING_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: web3PollingInterval
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.serverConfigName" . }}
                  key: clientUrl
          args:
            - "npm"
            - "run"
            - "start:server"
          livenessProbe:
              httpGet:
                  path: /
                  port: {{ .Values.server.config.port  | default 8000 }}
              initialDelaySeconds: 120
              periodSeconds: 30
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}