{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-server"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.config.port  | default 8000 }}
      targetPort: {{ .Values.server.config.port  | default 8000 }}
      protocol: TCP
      name: http
    - port: {{ .Values.server.config.metricsPort  | default 9091 }}
      targetPort: {{ .Values.server.config.metricsPort  | default 9091 }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    aragon.org/application: "{{ include "chart.name" . }}-server"
    aragon.org/environment: "{{ .Values.environment }}"
{{- end -}}