{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chart.secretName" . }}
type: Opaque
data:
  db_host: {{ .Values.secret.db_host | default "default" | b64enc }}
  db_name: {{ .Values.secret.db_name | default "default" | b64enc }}
  db_pass: {{ .Values.secret.db_pass | default "default" | b64enc }}
  db_port: {{ .Values.secret.db_port | default "default" | b64enc }}
  db_user: {{ .Values.secret.db_user | default "default" | b64enc }}
  google_credentials.json: {{ .Values.secret.google_credentials | default "default" | b64enc }}
{{- end -}}